name: Docker Push Auth

on:
  push:
    branches:
      - main # Or your auth service's main branch
    paths:
      - '/**' # Or a more specific path if your Dockerfile is nested

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (auth)
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./Dockerfile # Assuming Dockerfile is at the root
          context: ./          # Context is the root directory
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/trading-authorisation:latest
          # Add build-args if needed